name: dependency-updater

on:
  workflow_call:
    inputs:
      update-path:
        type: string
        description: Path to directory to run the update-command. If not provided defaults to root
        required: false
      on-changes-command:
        type: string
        description: Command to run if dependencies update and changes were detected. This can be version increments or extra checks.
        required: false
    
jobs:
  autoupdate_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.11"
      - uses: Gr1N/setup-poetry@v8
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - name: Print Poetry version
        shell: bash
        run: poetry --version
      - name: Install poetry relax plugin
        shell: bash
        run: poetry self add poetry-relax
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.DEPENDENCY_UPDATER_PYTHON_ID }}
          private_key: ${{ secrets.DEPENDENCY_UPDATER_PYTHON_PRIVATE_KEY }}
      - name: Run autoupdate
        shell: bash
        env:
          update_command: "poetry relax --update"
          default_branch: ${{ github.event.repository.default_branch }}
        run: |
          ./autoupdate-dependencies.sh \
          ${{ steps.generate_token.outputs.token }} \
          "${update_command}" \
          "${default_branch}" \
          "${{ inputs.update-path }}?" \
          "${{ inputs.on-changes-command }}?"